import pandas as pd
import os
import time
from transformers import AutoModelForCausalLM, AutoTokenizer

# --- API Library Imports ---
from openai import OpenAI
import anthropic
MODEL_NAME = "Qwen/Qwen3-4B-Instruct-2507"

# 2. Load Tokenizer and Model (Outside the loop!)
print("Loading tokenizer and model into memory. This might take a moment...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype="auto",
    device_map="auto",
    cache_dir="/projects/p32143/cache/huggingface"  # Optional: specify a cache directory for faster subsequent loads
)

# ==========================================
# 1. API Configuration
# Set API keys as environment variables
# ==========================================
import os
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")

if not OPENAI_API_KEY or not ANTHROPIC_API_KEY:
    raise ValueError("OPENAI_API_KEY and ANTHROPIC_API_KEY environment variables must be set")

# Initialize clients
openai_client = OpenAI(api_key=OPENAI_API_KEY)
claude_client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

# ==========================================
# 2. Helper Functions
# ==========================================
def read_file(filepath):
    """Reads a text file and returns its content."""
    try:
        with open(filepath, 'r', encoding='utf-8') as file:
            return file.read().strip()
    except Exception as e:
        print(f"Error reading {filepath}: {e}")
        return ""

def build_prompt(text, explanation):
    """Constructs the prompt sent to the LLMs."""
    return f"""You are an expert linguist. I will provide you with a text and an explanation (hint) regarding its characteristics. 
Based on the text and the hint, decide whether the text was written by a Human or generated by an AI.

Text:
\"\"\"{text}\"\"\"

Hint (Explanation):
\"\"\"{explanation}\"\"\"

Reply strictly with ONLY ONE WORD: either "Human" or "AI". Do not include any punctuation or extra explanation."""

# ==========================================
# 3. LLM API Call Functions
# ==========================================
def ask_openai(prompt):
    try:
        response = openai_client.chat.completions.create(
            model="gpt-5.4-mini", # or gpt-4o-mini
            messages=[{"role": "user", "content": prompt}],
            temperature=0.0, # 0 for most deterministic output
            # max_tokens=5
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        print(f"OpenAI Error: {e}")
        return "ERROR"

def ask_claude(prompt):
    try:
        response = claude_client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=5,
            temperature=0.0,
            messages=[{"role": "user", "content": prompt}]
        )
        return response.content[0].text.strip()
    except Exception as e:
        print(f"Claude Error: {e}")
        return "ERROR"
    
def ask_qwen(prompt):
    
    messages = [
        {"role": "user", "content": prompt}
    ]
    
    formatted_text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )
    
    model_inputs = tokenizer([formatted_text], return_tensors="pt").to(model.device)
    
    # Generate the summary
    generated_ids = model.generate(
        **model_inputs,
        max_new_tokens=5,
        do_sample=False, # Enforces greedy decoding (temperature=0.0 equivalent)
        pad_token_id=tokenizer.eos_token_id
    )
    
    # Extract just the new generated tokens, ignoring the prompt
    output_ids = generated_ids[0][len(model_inputs.input_ids[0]):].tolist() 
    response = tokenizer.decode(output_ids, skip_special_tokens=True).strip()
    
    return response

# ==========================================
# 4. Main Pipeline Execution
# ==========================================
def run_evaluation_pipeline(input_csv, output_csv):
    print(f"Loading data from {input_csv}...")
    df = pd.read_csv(input_csv)
    
    # Create new columns to store the LLM decisions
    if 'gpt4_decision' not in df.columns:
        df['gpt4_decision'] = None
        df['claude_decision'] = None
        df['qwen_decision'] = None

    total_rows = len(df)
    base_dir = "/projects/p32143/RL_human_decision/text_data/social/"

    for index, row in df.iterrows():
        print(f"Processing row {index + 1}/{total_rows} (Stimulus ID: {row['stimulus_id']})...")
        
        # Read the text and explanation from local paths
        full_text_path = os.path.join(base_dir, row['text_path'])
        full_exp_path = os.path.join(base_dir, row['explanation_path'])

        text_content = read_file(full_text_path)
        explanation_content = read_file(full_exp_path)

        if not text_content or not explanation_content:
            print(f"Skipping row {index} due to missing files.")
            continue
            
        # Construct the prompt
        prompt = build_prompt(text_content, explanation_content)
        
        # Call LLMs (Only calling if the cell is currently empty, allowing you to pause/resume)
        if pd.isna(row['gpt4_decision']):
            df.at[index, 'gpt4_decision'] = ask_openai(prompt)
            
        if pd.isna(row['claude_decision']):
            df.at[index, 'claude_decision'] = ask_claude(prompt)
            
        if pd.isna(row['qwen_decision']):
            df.at[index, 'qwen_decision'] = ask_qwen(prompt)
            
        # Optional: Sleep for a split second to avoid hitting API rate limits
        time.sleep(0.5) 
        
        # Save progress every 10 rows just in case the script crashes
        if (index + 1) % 10 == 0:
            df.to_csv(output_csv, index=False)
            print(f"Progress saved to {output_csv}")
            # break

    # Final Save
    df.to_csv(output_csv, index=False)
    print("Pipeline complete! Final results saved.")

if __name__ == "__main__":
    # Your master CSV from the previous step
    INPUT_CSV = "/projects/p32143/RL_human_decision/text_data/social/master_stimuli_database_socialmedia.csv"
    
    # The new CSV file where LLM decisions will be appended
    OUTPUT_CSV = "llm_evaluated_stimuli.csv" 
    
    run_evaluation_pipeline(INPUT_CSV, OUTPUT_CSV)