"""
Prompt templates for policy generation and evaluation.

Two key templates:
1. POLICY_INSTRUCTION: What the policy generates (the explanation hint)
2. EVAL_PROMPT_TEMPLATE: The full evaluation prompt the probe sees (exact match to db_to_prompt.py)
"""

# ============================================================================
# Policy Generation Instruction
# ============================================================================
# Adapted from RL/inference.py but generalized to "text" instead of "Social Media post"
# (allows extension to other text domains like academic/books/news if needed in future)

POLICY_INSTRUCTION = """Task: Analyze the provided text for linguistic markers of AI or human authorship.

Constraints:
1. Start the response IMMEDIATELY with the bulleted list.
2. Do NOT provide an introduction, a final verdict, or a summary.
3. Do NOT group the bullet points into sub-headings (keep it a flat list).
4. Every bullet point MUST follow one of these two exact templates:
    - "Look for [linguistic category or type of phrasing]."
    - "Look for [linguistic category or type of phrasing] like '[short example]'."
5. When providing examples, you may list multiple words separated by commas (e.g., like "word 1", "word 2").
6. Do NOT use bolding, italics, or any special Markdown formatting.
7. Limit the output to exactly 2 to 6 bullet points.

Text:
```
{text}
```

Can you provide an explanation that tells the reader what to focus on?

Explanation:
"""


def build_policy_prompt(text: str, tokenizer) -> str:
    """
    Build the policy's generation prompt in Qwen instruct format.

    Args:
        text: The input text to analyze
        tokenizer: Qwen tokenizer with apply_chat_template method

    Returns:
        The formatted prompt string (with chat-template applied, ready for generation)
    """
    messages = [{"role": "user", "content": POLICY_INSTRUCTION.format(text=text)}]
    return tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )


# ============================================================================
# Evaluation Prompt Template
# ============================================================================
# MUST be character-for-character identical to db_to_prompt.py
# This is the prompt that feeds into the frozen extraction model + probe

EVAL_PROMPT_TEMPLATE = """You are tasked with detecting whether a given text is AI-generated or human-written.
Below is the text, followed by an explanation hint that may help in your prediction.

Text:
{text_content}

Explanation Hint:
{explanation_content}

Based on the text and the explanation hint, predict whether the text is AI-generated or human-written.
Output 1 for AI-generated or 0 for human-written. Output only the number 0 or 1."""


def build_eval_prompt(text_content: str, explanation_content: str) -> str:
    """
    Build the evaluation prompt for the frozen model + probe.

    This prompt is fed to the frozen Qwen3.6-27B (via AutoProcessor) to extract
    the last-token hidden state, which is then scored by the frozen probe.

    Args:
        text_content: The original text (human or AI)
        explanation_content: The explanation hint (generated by policy or from DB)

    Returns:
        The complete evaluation prompt string
    """
    return EVAL_PROMPT_TEMPLATE.format(
        text_content=text_content,
        explanation_content=explanation_content,
    )
